spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/disco
    username: disco
    password: disco123
    platform: postgres
jpa:
  database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  hibernate:
    format_sql: true
    ddl-auto: create

