spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/disco
    username: disco
    password: disco123
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always #init data.sql
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
    defer-datasource-initialization: true #hibernate 가 테이블을 생성한 이후 sql 실행하기 위함
